### PR TITLE
Add myself to map

### PR DESCRIPTION
**Pull request by IsaacAbrahamson**

### CODE REVIEW

**Comment by kuznetsovandrey76** [comment]
Hi, remove favicon cohort of photos 🙂

**Comment by IsaacAbrahamson** [comment]
Remove favicon cohort of photos? I am not sure what you mean, can you clarify that?

**Comment by kuznetsovandrey76** [comment]
remove red Panda from your image

**Comment by IsaacAbrahamson** [comment]
I understand now, thank you.
Image replaced!

**Pull request merged**
